services:
  dockernode:
    container_name: ${DOCKERNODE_CONTAINER_NAME:-ffdd-node}
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERNODE_IMAGE:-ffdd-node}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${FASTD_PORT:-5002}:${FASTD_PORT:-5002}/udp"
    volumes:
      - ./data:/data
    mem_limit: ${DOCKERNODE_MEM_LIMIT:-200m}
    stop_grace_period: 15s
    environment:
      NODE_CONTACT_EMAIL: ${NODE_CONTACT_EMAIL:-}
      NODE_NAME: ${NODE_NAME:-}
      NODE_CONTACT_NAME: ${NODE_CONTACT_NAME:-}
      NODE_CONTACT_LOCATION: ${NODE_CONTACT_LOCATION:-}
      NODE_CONTACT_NOTE: ${NODE_CONTACT_NOTE:-}
      NODE_COMMUNITY: ${NODE_COMMUNITY:-Dresden}
      NODE_GPS_LATITUDE: ${NODE_GPS_LATITUDE:-}
      NODE_GPS_LONGITUDE: ${NODE_GPS_LONGITUDE:-}
      NODE_GPS_ALTITUDE: ${NODE_GPS_ALTITUDE:-0}
      FASTD_PORT: ${FASTD_PORT:-5002}
      REGISTRAR_INTERVAL: ${REGISTRAR_INTERVAL:-3600}
      FASTD_PEERS: ${FASTD_PEERS:-}
      NODE_REGISTRATION_URL: ${NODE_REGISTRATION_URL:-}
      BMXD_PREFERRED_GATEWAY: ${BMXD_PREFERRED_GATEWAY:-}
      FAILFAST_CHECKS: ${FAILFAST_CHECKS:-}