user nginx;
worker_processes 1;
error_log /proc/self/fd/2 warn;
pid /var/run/nginx.pid;

events {
    worker_connections 64;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    absolute_redirect off;

    access_log off;
    sendfile on;
    keepalive_timeout 15;

    server {
        listen 80;
        root /run/freifunk/www;
        autoindex off;

        location = /sysinfo.json {
            default_type application/json;
            try_files /sysinfo.json =404;
        }

        location = /sysinfo-json.cgi {
            default_type application/json;
            try_files /sysinfo-json.cgi =404;
        }

        location = /nodes.json {
            default_type application/json;
            try_files /nodes.json =404;
        }

        location = /mesh-status.json {
            default_type application/json;
            try_files /mesh-status.json =404;
        }

        location = / {
            return 302 /ui/;
        }

        location /ui/ {
            try_files $uri $uri/ /ui/index.html;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
